"""Criando tabelas iniciais

Revision ID: 4dc664ec1dd4
Revises: 
Create Date: 2026-06-21 17:06:41.315778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc664ec1dd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('regime', sa.Enum('CLT', 'PJ', 'ESTAGIO', 'AUTONOMO', name='regimetrabalho'), nullable=False),
    sa.Column('carga_horaria_diaria', sa.Integer(), nullable=False),
    sa.Column('valor_hora', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('jornadas_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('saldo_horas', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jornadas_diarias_id'), 'jornadas_diarias', ['id'], unique=False)
    op.create_index(op.f('ix_jornadas_diarias_id_user'), 'jornadas_diarias', ['id_user'], unique=False)
    op.create_table('registros_pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_jornada', sa.Integer(), nullable=True),
    sa.Column('horario', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registro', sa.Enum('ENTRADA', 'ALMOCO_SAIDA', 'ALMOCO_ENTRADA', 'SAIDA', name='pontosbatidos'), nullable=False),
    sa.ForeignKeyConstraint(['id_jornada'], ['jornadas_diarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_pontos_id'), 'registros_pontos', ['id'], unique=False)
    op.create_index(op.f('ix_registros_pontos_id_jornada'), 'registros_pontos', ['id_jornada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_pontos_id_jornada'), table_name='registros_pontos')
    op.drop_index(op.f('ix_registros_pontos_id'), table_name='registros_pontos')
    op.drop_table('registros_pontos')
    op.drop_index(op.f('ix_jornadas_diarias_id_user'), table_name='jornadas_diarias')
    op.drop_index(op.f('ix_jornadas_diarias_id'), table_name='jornadas_diarias')
    op.drop_table('jornadas_diarias')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
